### ISSUE TITLE
What is the difference between this and laravel-phpredis from vetruvet?

### ISSUE THREAD

**Issue by Swanty** [tillkruss/laravel-phpredis#1]
There is a more popular repository https://github.com/vetruvet/laravel-phpredis
Is there a reason why you created a new one other than the returning null instead of false if key doesn't exist?

Also the other repository supports sharding? https://github.com/vetruvet/laravel-phpredis/blob/master/src/Vetruvet/PhpRedis/Database.php#L10-L70

Which one would be better to use yours or the other one?

**Comment by tillkruss** [comment]
I'd give both a try.

If you encounter weird results with other packages, especially with `Cache::has()` returning true even if the cache key doesn't exists, then try this package.

~~I can add `RedisArray` support to this package, but it seems like Clustering with PhpRedis is not production ready, yet: https://github.com/phpredis/phpredis/issues/214~~

This package uses `RedisCluster` instead of `RedisArray` for clustering.
